### PR TITLE
Add auth support

### PR DESCRIPTION
**Pull request by dankinsoid**
Add auth support for Grafana Cloud, add "level" label and move metadata from message to labels

### CODE REVIEW

**Comment by lovetodream** [comment]
Seems like you're still working on this, I'll convert it to draft for now. Just let me know once you're ready

**Comment by dankinsoid** [comment]
@lovetodream I'm ready
I created the `LokiAuth` struct and Basic auth implementation
Also, I added the `lokiLabel` var for `LoggerMetadata` to add metadata as custom loki labels
And I added "level" label

**Comment by lovetodream** [comment]
Even though I see why you'd like to add auth support, but I think consumers of the library should handle authentication by themself. This library should be as unopinionated as possible, doing just the things it really needs to do. Thank you for the effort.

**Comment by dankinsoid** [comment]
@lovetodream Is there even a way to use Loki at Grafana Cloud without authentication?

**Comment by lovetodream** [comment]
> @lovetodream Is there even a way to use Loki at Grafana Cloud without authentication?

I don't think so, but you can add your Authorization header to to `headers` array in the `LokiLogHandler` initializer.

**Pull request closed without merging**
